### ISSUE TITLE
GShade is not properly removed

### ISSUE THREAD

**Issue by Lexden12** [parkel42/gshade-migration#1]
Using else if for [these](https://github.com/parkel42/gshade-migration/blob/3152c70cc57553022b91a6ace73dd2954df17c7b/gshade-migration.ps1#L54) three occurrences means that not all GShade artifacts may be deleted. Replace with if to ensure proper removal.

**Comment by Lexden12** [comment]
I have a commit available with a fix, but you have locked down the permissions on your repo.

**Comment by parkel42** [comment]
Oops. Updated the code. Thanks for letting me know!
