### ISSUE TITLE
Not working due to illegal symbols - at least in german windows

### ISSUE THREAD

**Issue by Gabbalo** [parkel42/gshade-migration#2]
The code makes heavy use of the ampersand sign (&), which seems to be not allowed in code tdue to reservation for future use, same goes for "<" and ">".

`
In C:\Users\user\Downloads\gshade-migration.ps1:210 Zeichen:162
 ... t="true" class="Header-link js-details-target btn-link">    <svg aria ...
                                                                 ~
Der Operator "<" ist für zukünftige Versionen reserviert.
In C:\Users\user\Downloads\gshade-migration.ps1:213 Zeichen:14
 </button>    </div>
              ~
Der Operator "<" ist für zukünftige Versionen reserviert.
In C:\Users\user\Downloads\gshade-migration.ps1:456 Zeichen:31
         data-analytics-event="{&quot;category&quot;:&quot;Header&quot ...
                               ~
Unerwartetes Token "{" in Ausdruck oder Anweisung.
In C:\Users\user\Downloads\gshade-migration.ps1:456 Zeichen:46
         data-analytics-event="{&quot;category&quot;:&quot;Header&quot ...
                                              ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert. Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu übergeben.
In C:\Users\user\Downloads\gshade-migration.ps1:456 Zeichen:53
         data-analytics-event="{&quot;category&quot;:&quot;Header&quot ...
                                                     ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert. Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu übergeben.
In C:\Users\user\Downloads\gshade-migration.ps1:456 Zeichen:65
 ...     data-analytics-event="{&quot;category&quot;:&quot;Header&quot;,&q ...
                                                                 ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert. Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu übergeben.
In C:\Users\user\Downloads\gshade-migration.ps1:456 Zeichen:72
 ... ta-analytics-event="{&quot;category&quot;:&quot;Header&quot;,&quot;ac ...
                                                                  ~
Ausdruck fehlt nach dem unären Operator ",".
In C:\Users\user\Downloads\gshade-migration.ps1:456 Zeichen:72
 ... a-analytics-event="{&quot;category&quot;:&quot;Header&quot;,&quot;act ...
                                                                 ~
Unerwartetes Token "&" in Ausdruck oder Anweisung.
In C:\Users\user\Downloads\gshade-migration.ps1:456 Zeichen:84
 ... event="{&quot;category&quot;:&quot;Header&quot;,&quot;action&quot;:&q ...
                                                                 ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert. Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu übergeben.
In C:\Users\user\Downloads\gshade-migration.ps1:456 Zeichen:91
 ... {&quot;category&quot;:&quot;Header&quot;,&quot;action&quot;:&quot;sig ...
                                                                 ~
Das kaufmännische Und-Zeichen (&) ist nicht zulässig. Der &-Operator ist für eine zukünftige Verwendung reserviert. Verwenden Sie das kaufmännische Und-Zeichen in doppelten Anführungszeichen ("&"), um es als Teil einer Zeichenfolge zu übergeben.
Es wurden nicht alle Analysefehler berichtet. Korrigieren Sie die berichteten Fehler, und versuchen Sie es erneut.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : RedirectionNotSupported
`

(sorry, the "code" is so f*cked up, but Markdown and PS error output doesn't seem to like each other ... lots of plusses (+) in the output -.-)

**Comment by parkel42** [comment]
Hmm that is weird. I google translated the error message(s) and noticed that it apart from `&`s there were also some redirection stuff (`>`s and `<`s) going on which I don't use in the script. 

I'm not sure if this would solve the issue, but could you try to download the script from the following link instead?

[gshade-migration-main.zip](https://github.com/parkel42/gshade-migration/files/10696081/gshade-migration-main.zip)

**Comment by parkel42** [comment]
Oops closed by accident.

**Comment by Gabbalo** [comment]
Can be closed by intention because of my stupidity.

Yes, I don't run Scripts from the internet without checking them ... no, I don't check them AGAIN AFTER download ...
If you download the script by "save link as ..." it saves the page, not the script ... hence its a webpage -.-

So most probably no real issue ... and since I migrated manually now, I cannot retest it. 

Sry for inconvinience

**Comment by parkel42** [comment]
Well it happens! No worries at all.
