### ISSUE TITLE
ReShade 5.60 failed to download

### ISSUE THREAD

**Issue by SelfAfflicted** [parkel42/gshade-migration#3]
Seems the URL path to the exe file has changed, removing _static_ did the trick, however, I only realized this after uninstalling gshade, so I had to edit the script and remove all the lines prior to that point. I think it'd be better to have the script attempt to download the necessary files before proceeding with uninstalling anything, that way the process can be halted before such an occurrence happens. Though, that being said, I'm sure for most who were effected by this have already migrated to ReShade.

**Comment by parkel42** [comment]
Thanks! That's a good point. Even though this script probably isn't needed as much, I have still made the changes.
